### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by rksh1997** [mohamad-tumeh/DataGrid-React#1]
Hi, I’ve had a chance to review your code, and I see some areas that need improvement:
 
1. There are tons of unused packages in `package.json`. This increases pipeline time on gitlab which means paying more money.

2. Installing dependencies in devDependencies (like emotion and react-resizable)

3. There are unimplemented requirements
  a. I can't change a column name, I tried it a lot and it's not working.

4. On initial page load, I see Page size select empty and there's an empty option when I open the select

5. On loading state, the page has a scrollbar because it's more than `100vh` (because you have h1 on top)

6. You are mixing uses of `<div style={...} />` and `<Box sx={...} />` which is not acceptable

7. **The task emphasizes that 70% of the final grading is on style, however, I see that you've not written a single line of css to 
make it beautiful. You simply used the apline theme which is used by 100k other devs.**

8. In `Table.tsx` I see a `useEffect` that's 27 lines of code!!

9. You are putting some common functions inside `Table.tsx` like `getColumnType`. Also what about `Date` type?

10. **The error state is just red text!! I don't think that satisfies the (70% must be beautiful) part of the assessment.**

11. empty state is like 2 times my screen high, why?

12. ` rowData: any[];` ... `any` is forbidden in such cases

13. Why are you using html like `h1` `p` while you have material UI?

I appreciate the effort you’ve put into it. Based on the current state, I would give it a 3/10. However, I want to thank you for your time and dedication, and I encourage you to give it another try if you're open to revisiting the task!

**Comment by mohamad-tumeh** [comment]
Welcome ,
 I will reconsider this task, Thank you for these comments, I will not be
late

**Comment by mohamad-tumeh** [comment]
Welcome,
thank you very much for your useful comments.
 I have uploaded a new version on github.
 Please review again. Thank you very much for your time.

**Comment by rksh1997** [comment]
Hi Mohamed,

Thank you once again for your effort on the assessment. I appreciate the work you’ve put in.

However, I noticed that while some issues were addressed, a few others remain unresolved. For example, **the issue with the scrollbars still persists, and the column type, which is a required feature, has been removed.**

Additionally, as 70% of the grading is focused the beautiness of the UI, I have to be honest in saying that it doesn’t quite meet the visual standards we’re looking for.

I want to be transparent with you—while I see potential and the effort you've invested, the requirements for this particular project call for developers with over 5 years of frontend experience. That said, I believe you could be a great fit for other projects within the company, but unfortunately, not this one.

My general advice would be to take your time with assessments, ensuring everything is polished before submitting. I’m confident this approach will help you in future endeavors.

Wish you the best,
Rashad.

**Comment by mohamad-tumeh** [comment]
Hello Rashad
, Thank you. I benefited greatly from the comments you gave me. Thank you
for all the comments
